# Generated by Django 4.2.6 on 2023-10-31 04:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at'),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Updated at'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Updated at'),
        ),
    ]
