version: '3'

services:
  social-db:
    image: postgres
    #    platform: linux/amd64
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=social_db
    expose:
      - 5432
    ports:
      - "5432:5432"
    command: -p 5432
    restart: always

    volumes:
      - dbdata:/var/lib/postgresql/data
      - db_backup:/var/lib/postgresql/backup

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - social-db
    command: sh -c "python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"

    volumes:
      - .:/app/backend
    expose:
      - 8000
    ports:
      - "8000:8000"
    restart: always

volumes:
  dbdata:
  db_backup: