# Generated by Django 4.2.6 on 2023-10-31 05:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0002_alter_friend_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendshiprequest',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at'),
        ),
    ]
